<?php

return [
    'major_airports' => [
        'YUL' => 'Montreal-Trudeau',
        'YYZ' => 'Toronto-Pearson',
        'JFK' => 'New York-JFK',
        'LHR' => 'London-Heathrow',
        'CDG' => 'Paris-Charles de Gaulle',
        'NRT' => 'Tokyo-Narita',
        'DCA' => 'Washington-Reagan',
        'LAX' => 'Los Angeles',
    ],
    
    'major_airlines' => [
        'AC' => 'Air Canada',
        'AA' => 'American Airlines',
        'DL' => 'Delta Air Lines',
        'UA' => 'United Airlines',
        'WS' => 'WestJet',
        'BA' => 'British Airways',
        'AF' => 'Air France',
        'LH' => 'Lufthansa',
        'KL' => 'KLM Royal Dutch Airlines',
        'SQ' => 'Singapore Airlines',
        'EK' => 'Emirates',
        'QR' => 'Qatar Airways',
        'TK' => 'Turkish Airlines',
        'AZ' => 'Alitalia',
        'IB' => 'Iberia',
        'VS' => 'Virgin Atlantic',
        'JL' => 'Japan Airlines',
        'NH' => 'All Nippon Airways',
        'CX' => 'Cathay Pacific',
        'SV' => 'Saudi Arabian Airlines',
        'ET' => 'Ethiopian Airlines',
        'MS' => 'EgyptAir',
        'RJ' => 'Royal Jordanian',
        'ME' => 'Middle East Airlines',
        'QF' => 'Qantas',
        'NZ' => 'Air New Zealand',
        'SK' => 'Scandinavian Airlines',
        'AY' => 'Finnair',
        'OS' => 'Austrian Airlines',
        'LX' => 'Swiss International Air Lines',
    ],
];