export const MAJOR_CITIES = {
    'YMQ': "Montreal", 
    'YTO' : "Toronto", 
    'NYC': "New York", 
    'LON': "London", 
    'PAR': "Paris", 
    'TYO': "Tokyo", 
    'WAS': "Washington", 
    'LAX': "Los Angeles", 
    'CHI': "Chicago", 
    'MIA': "Miami", 
    'DFW': "Dallas/Fort Worth", 
    'ATL': "Atlanta", 
    'SFO': "San Francisco", 
    'DEN': "Denver", 
    'SEA': "Seattle", 
    'BOS': "Boston", 
    'LAS': "Las Vegas", 
} as const
  